In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
file_name2='C:/Users/ostina/Documents/ES/fianl/funcom_processed/dump/comment.csv'
file_name1='C:/Users/ostina/Documents/ES/fianl/funcom_processed/dump/functions.csv'

In [3]:
file1 = open(file_name1, "r",encoding="utf8")
file2 = open(file_name2, "r",encoding="utf8")

In [4]:
corpus1=file1
corpus2=file2

In [5]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus1)
print(vectorizer.get_feature_names())
r,c=X.shape
print(r)
print(X[0:5])

['1000', '14', '70000', '__dft', '__eq__', '__init__', '__multiply', '__setitem__', '__str__', '_algorithm', '_calculate_k_matrix', '_check_obey_kkt', '_choose_alphas', '_e', '_fib', '_get_new_alpha', '_k', '_modexpt', '_norm', '_normalizegraph', '_predict', 'a1', 'a2', 'accuracy', 'actual', 'actual_y', 'add', 'add_edge', 'add_pair', 'add_row', 'alpha', 'alternative_password_generator', 'any', 'arr', 'array', 'base', 'block', 'bool', 'bottom_to_top', 'breadth_first_search', 'calculate_mean', 'calculate_probabilities', 'calculate_variance', 'check_bipartite_dfs', 'check_circuit_or_path', 'checkbipartite', 'chinese_remainder_theorem', 'chinese_remainder_theorem2', 'cipher_text', 'circle', 'class_count', 'classify', 'col', 'columns', 'common_diff', 'computeap', 'computebridges', 'cost', 'ctbi', 'data', 'def', 'depth_first_search', 'dfs', 'e1', 'e2', 'e741', 'emitterconverter', 'encoding', 'end', 'errors', 'evaluate', 'expand_block', 'exponent', 'extended_euclid', 'fetch_from_to', 'fetch_l

In [6]:
y = vectorizer.fit_transform(corpus2)
#print(vectorizer.get_feature_names())
print(y.shape)
print(y[0:5])

(120, 322)
  (0, 54)	1.0
  (1, 100)	0.7071067811865476
  (1, 108)	0.7071067811865476
  (2, 151)	0.4702043243070732
  (2, 112)	0.4190688544305941
  (2, 293)	0.2854304783254993
  (2, 109)	0.5107928301630882
  (2, 307)	0.5107928301630882
  (3, 204)	0.29408822048372646
  (3, 290)	0.25247363249441357
  (3, 122)	0.32540809418322547
  (3, 291)	0.47776396568377444
  (3, 151)	0.5360615094334401
  (3, 112)	0.47776396568377444
  (4, 152)	0.5453401677755829
  (4, 308)	0.4279270218897223
  (4, 5)	0.5453401677755829
  (4, 256)	0.4712607205757673


In [7]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [8]:
print(X.shape)
temp=np.zeros([120,322])
#temp=zeros(120,101)
print(temp.shape)
for i in range (119):
    for j in range (220):
        temp[i,j]=X[i,j];
        if temp[i,j]>0:
            print(i,j,temp[i,j])
#X = np.concatenate((X,temp))
print(temp.shape)
print(temp)
X = temp.copy()

(120, 221)
(120, 322)
0 87 1.0
1 60 0.0783321505062868
1 73 0.3964112889296219
1 106 0.8549558797748033
1 207 0.3252270097096923
2 46 0.2923949401840794
2 60 0.05777818417739952
2 106 0.7882746414771074
2 133 0.2691607187128395
2 134 0.2691607187128395
2 165 0.2691607187128395
2 166 0.2691607187128395
3 60 0.10335199438343137
3 106 0.8460261340342816
3 107 0.5230278632998198
4 47 0.2923949401840794
4 60 0.05777818417739952
4 106 0.7882746414771074
4 133 0.2691607187128395
4 134 0.2691607187128395
4 165 0.2691607187128395
4 166 0.2691607187128395
5 26 0.9748386230789886
5 60 0.22291177392291725
6 26 0.9748386230789886
6 60 0.22291177392291725
7 26 0.9748386230789886
7 60 0.22291177392291725
8 60 0.07494564656398148
8 89 0.379273391092555
8 113 0.349135653547422
8 130 0.349135653547422
8 187 0.7789373759900662
9 48 0.353032143562881
9 60 0.07578206919962904
9 114 0.353032143562881
9 130 0.353032143562881
9 187 0.7876306208001407
10 48 0.349135653547422
10 60 0.07494564656398148
10 114 0.

In [9]:
print(y.shape)
print(temp.shape)

(120, 322)
(120, 322)


In [10]:

import numpy as np
from scipy.sparse import csr_matrix
import pandas as pd
y0=y.todense()
X0 = csr_matrix(X)
#X0=X.todense()
X1=X0*100
X1=X1.astype(int)
y1=y0*100
y1=y1.astype(int)
print(X1.shape)
print(y1.shape)
print(y1)

(120, 322)
(120, 322)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
Y_dev = y1[0:30]
X_dev =X1[0:30]
print(Y_dev.shape)
print(X_dev.shape)
#print(X_dev)
print(Y_dev[2:])

(30, 322)
(30, 322)
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 33  0  0]]


In [12]:
X_train=X1[31:120]
X_train=X_train.T
Y_train = y1[31:120]
_,m_train = X_train.shape
print(X_train)

  (60, 0)	8
  (82, 0)	29
  (116, 0)	27
  (149, 0)	42
  (176, 0)	42
  (187, 0)	58
  (207, 0)	35
  (55, 1)	57
  (60, 1)	11
  (65, 1)	57
  (141, 1)	57
  (57, 2)	40
  (60, 2)	8
  (92, 2)	40
  (94, 2)	40
  (98, 2)	40
  (103, 2)	40
  (175, 2)	40
  (60, 3)	15
  (77, 3)	80
  (93, 3)	56
  (45, 4)	80
  (60, 4)	15
  (93, 4)	56
  (43, 5)	80
  :	:
  (140, 81)	39
  (153, 81)	52
  (205, 81)	52
  (60, 82)	10
  (104, 82)	51
  (112, 82)	51
  (116, 82)	67
  (60, 83)	20
  (122, 83)	97
  (5, 84)	59
  (60, 84)	15
  (177, 84)	31
  (212, 84)	72
  (60, 85)	16
  (75, 85)	81
  (187, 85)	55
  (60, 86)	10
  (68, 86)	53
  (74, 86)	53
  (116, 86)	34
  (185, 86)	53
  (60, 87)	10
  (90, 87)	51
  (187, 87)	70
  (210, 87)	47


In [13]:
def init_params():
    W1 = np.random.rand(322, 221) - 0.5
    b1 = np.random.rand(322, 1) - 0.5
    W2 = np.random.rand(322, 322) - 0.5
    b2 = np.random.rand(322, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    if Z.any()>0:
        return Z
    else:
        return 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    #one_hot_Y = one_hot(Y)
    m=89
    dZ2 = A2 - Y.T
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    #dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dZ1 = W2.T.dot(dZ2) * Z1
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [16]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [17]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 20)
print(W1, b1, W2, b2)

SystemError: <built-in function isinstance> returned a result with an error set